// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using routine_explorer.Data;

namespace routine_explorer.Migrations.Database
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("routine_explorer.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActionDateTime");

                    b.Property<string>("AreaAccessed")
                        .IsRequired();

                    b.Property<string>("UserIP")
                        .IsRequired();

                    b.Property<string>("UserLocation")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("routine_explorer.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Suggestion")
                        .IsRequired();

                    b.Property<string>("UserEmail")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<int>("UserRating");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("routine_explorer.Models.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseCode")
                        .IsRequired();

                    b.Property<string>("DayOfWeek")
                        .IsRequired();

                    b.Property<string>("RoomNumber")
                        .IsRequired();

                    b.Property<int>("StatusId");

                    b.Property<string>("Teacher")
                        .IsRequired();

                    b.Property<string>("TimeRange")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Routine");
                });

            modelBuilder.Entity("routine_explorer.Models.RoutineFileUploaderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NameOfFilesUploaded")
                        .IsRequired();

                    b.Property<DateTime>("TimeOfUpload");

                    b.Property<bool>("statusOfPublish");

                    b.HasKey("Id");

                    b.ToTable("RoutineFileUploaderStatus");
                });

            modelBuilder.Entity("routine_explorer.Models.Routine", b =>
                {
                    b.HasOne("routine_explorer.Models.RoutineFileUploaderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
